apiVersion: apps/v1
kind: Deployment
metadata:
  name: manifest-nginx-git-public
  labels:
    app: nginx-public
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-public
  template:
    metadata:
      labels:
        app: nginx-public
    spec:
      containers:
      - name: nginx-public
        image: nginx:1.14.2
        ports:
        - containerPort: 80
